config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    # mount_devise_token_auth_for "User", at: "auth"

    mount_devise_token_auth_for "User", at: "auth", controllers: {
      registrations: "api/users/registrations",
      sessions: "api/users/sessions",
      confirmations: "api/users/confirmations"
    }
    resources :posts, only: [:index]
  end

  devise_for :users
  namespace :admin do
    resources :users
    resources :groups
    resources :posts do
      resources :comments
    end
    # routes for admin
    get 'dashboard/' => 'dashboard#index'
    get 'users/index'
  end
  resources :posts
  resources :groups

  resources :users  do
    member do
      post :follow
      post :unfollow
    end
  end
  
  root 'posts#index'


end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  validates :name, presence: true
  paginates_per 20
  belongs_to :user, optional: true
  has_many :posts, dependent: :destroy
  has_many :group_members
  has_many :members, through: :group_members, source: :user

  enum :privacy, { publics: 0, privates: 1 }
end

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

module Admin
  class GroupsController < Admin::BaseController
    before_action :set_group, only: %i[show edit update destroy]

    def index
      @q = Group.ransack(params[:q])
      @groups = @q.result.includes(:user).page(params[:page])
    end

    def show; end

    def new
      @group = Group.new
    end

    def edit; end

    def create
      @group = current_user.groups.build(group_params)

      if @group.save
        redirect_to group_url(@group), notice: 'Group was successfully created.'
      else
        render :new
      end
    end

    def update
      if @group.update(group_params)
        redirect_to group_url(@group), notice: 'Group was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @group.destroy

      redirect_to admin_groups_url, notice: 'Group was successfully destroyed.'
    end

    private

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :privacy).merge(user_id: current_user.id)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :must_be_admin, only: %i[edit update destroy]

  def index
    @q = Group.ransack(params[:q])
    @groups = @q.result.includes(:user).page(params[:page])
  end

  def show; end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to group_url(@group), notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_url(@group), notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy

    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description, :privacy).merge(user_id: current_user.id)
  end

  def must_be_admin
    unless current_user.id == @group.user_id || current_user.admin?
      redirect_to root_path, notice: 'Not the creator of this group!'
    end
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <p>
    <b>Privacy</b><br />
    <%= form.radio_button :privacy, 'privates' %> Private<br />
    <%= form.radio_button :privacy, 'publics' %> Public<br />
    
  </p>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= @group.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @group.description %>
  </p>

  <p>
    <h2>Posts: <h2>
    <% @group.posts.all.each do |post| %>
        <h3><%= post.title %></h3>
        <p><%= post.content %></p>
        <br>
    <% end %>
  </p>

  <p>
  <h2>Members: <h2>
  <% @group.members.each do |member| %>
      <h3><%= member.username %></h3>
      <p><%= member.email %></p>
      <br>
  <% end %>
</p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<%= paginate @groups, window: 2 %>

<%= search_form_for @q, remote: true do |f| %>
  <%= f.label :name_cont, 'Group Name' %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>

<table id="group_list_table" class="table table-striped table-bordered dataTable no-footer" cellspacing="0" role="grid"
  aria-describedby="list_group_table_info">
  <thead>
    <tr>
      <th>Group Name</th>
      <th>Privacy</th>
      <th>Created At</th>
      <th>Total Members</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <% if group.privacy=:publics || current_user.id == group.user_id %>
        <tr style="white-space: initial; overflow: auto">
          <td><%= group.name %></td>
          <td><%= group.privacy %></td>
          <td><%= group.created_at %></td>
          <td><%= group.members.count %></td>
          <td><%= link_to "Details", group_path(group) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<br>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>