config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    # mount_devise_token_auth_for "User", at: "auth"

    mount_devise_token_auth_for "User", at: "auth", controllers: {
      registrations: "api/users/registrations",
      sessions: "api/users/sessions",
      confirmations: "api/users/confirmations"
    }
    resources :posts, only: [:index]
  end

  devise_for :users
  namespace :admin do
    resources :users
    resources :groups
    resources :posts do
      resources :comments
    end
    # routes for admin
    get 'dashboard/' => 'dashboard#index'
    get 'users/index'
  end
  resources :posts
  resources :groups

  resources :users  do
    member do
      post :follow
      post :unfollow
    end
  end
  
  root 'posts#index'


end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
  extend Devise::Models

  paginates_per 10
  has_many :comments, dependent: :destroy
  has_many :post_votings, dependent: :destroy
  has_many :posts,  dependent: :destroy
  has_many :groups, dependent: :destroy

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Relationship'
  has_many :followeds, through: :followed_users
  has_many :following_users, foreign_key: :followed_id, class_name: 'Relationship'
  has_many :followers, through: :following_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :email, presence: true
  has_many :posts

  def search_posts(title)
    if title.present?
      posts.where("posts.title LIKE ?", "%#{title}%")
    else
      posts
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.full_name = auth.info.name # assuming the user model has a name
      # user.avatar_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_one_attached :avatar

  validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
  validate :birthday_cannot_be_in_the_future
  def birthday_cannot_be_in_the_future
    errors.add(:birthday, "can't be in the past") if birthday.present? && birthday > Date.today
  end

  def self.search(search)
    where('username LIKE :query OR email LIKE :query', { query: "%#{search}%" })
  end

  def self.status(status)
    where('status LIKE :query', { query: "%#{status}%" })
  end

  enum :status, { permit: 0, ban: 1 }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::BaseController
    before_action :get_user, only: %i[show edit update destroy]
    before_action :set_q, only: %i[index]

    def index
      @users = @q.result(distinct: true).page(params[:page]).where.not(admin: true)
    end

    def show; end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = 'User successfully created'
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def edit; end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render 'edit'
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path
    end

    private

    def set_q
      @q = User.ransack(params[:q])
    end

    def get_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:avatar, :username, :email, :birthday, :status, :password,
                                   :password_confirmation)
    end
  end
end

app/controllers/api/users/registrations_controller.rb
# frozen_string_literal: true

class Api::Users::RegistrationsController < DeviseTokenAuth::RegistrationsController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_user_by_token, only: [:destroy, :update]
  before_action :validate_sign_up_params, only: :create
  before_action :validate_account_update_params, only: :update
  skip_after_action :update_auth_header, only: [:create, :destroy]

  def create
    build_resource

    unless @resource.present?
      raise DeviseTokenAuth::Errors::NoResourceDefinedError,
            "#{self.class.name} #build_resource does not define @resource,"\
            ' execution stopped.'
    end

    # # give redirect value from params priority
    # @redirect_url = params.fetch(
    #   :confirm_success_url,
    #   DeviseTokenAuth.default_confirm_success_url
    # )

    # # success redirect url is required
    # if confirmable_enabled? && !@redirect_url
    #   return render_create_error_missing_confirm_success_url
    # end

    # # if whitelist is set, validate redirect_url against whitelist
    # return render_create_error_redirect_url_not_allowed if blacklisted_redirect_url?(@redirect_url)

    # override email confirmation, must be sent manually from ctrl
    callback_name = defined?(ActiveRecord) && resource_class < ActiveRecord::Base ? :commit : :create
    resource_class.set_callback(callback_name, :after, :send_on_create_confirmation_instructions)
    resource_class.skip_callback(callback_name, :after, :send_on_create_confirmation_instructions)

    if @resource.respond_to? :skip_confirmation_notification!
      # Fix duplicate e-mails by disabling Devise confirmation e-mail
      @resource.skip_confirmation_notification!
    end

    if @resource.save
      yield @resource if block_given?

      # unless @resource.confirmed?
      #   # user will require email authentication
      #   @resource.send_confirmation_instructions({
      #     client_config: params[:config_name],
      #     redirect_url: @redirect_url
      #   })
      # end
      @resource.confirm

      if active_for_authentication?
        # email auth has been bypassed, authenticate user
        @token = @resource.create_token
        @resource.save!
        update_auth_header
      end

      render_create_success
    else
      clean_up_passwords @resource
      render_create_error
    end
  end
end

app/controllers/api/users/sessions_controller.rb
# frozen_string_literal: true

class Api::Users::SessionsController < DeviseTokenAuth::SessionsController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    field = (resource_params.keys.map(&:to_sym) & resource_class.authentication_keys).first

    @resource = nil
    if field
      q_value = get_case_insensitive_field_from_resource_params(field)

      @resource = find_resource(field, q_value)
    end

    if @resource && valid_params?(field,
      q_value) && (!@resource.respond_to?(:active_for_authentication?) || @resource.active_for_authentication?)
      valid_password = @resource.valid_password?(resource_params[:password])
      if (@resource.respond_to?(:valid_for_authentication?) && !@resource.valid_for_authentication? do
            valid_password
          end) || !valid_password
        return render_create_error_bad_credentials
      end
      @token = @resource.create_token
      @resource.save

      sign_in(:user, @resource, store: false, bypass: false)

      yield @resource if block_given?

      render_create_success
    elsif @resource && !(!@resource.respond_to?(:active_for_authentication?) || @resource.active_for_authentication?)
      if @resource.respond_to?(:locked_at) && @resource.locked_at
        render_create_error_account_locked
      else
        render_create_error_not_confirmed
      end
    else
      render_create_error_bad_credentials
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      handle_auth 'Google'
    end

    def handle_auth(kind)
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.auth_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_path, alert: @user.errors.full_message.join("\n")
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
    def update_resource(resource, params)
      if resource.provider == 'google_oauth2'
        params.delete('current_password')
        resource.password = params['password']

        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
    def after_sign_out_path_for(_resource_or_scope)
      new_user_session_path
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :get_user, only: %i[show follow unfollow]
  def index
    @users = User.where.not(admin: true)
  end

  def show
    @public_posts = @user.posts.public_posts
    @private_posts = @user.posts.private_posts
    @pending_posts = @user.posts.pending_posts
  end

  def follow
    current_user.followeds << @user
    redirect_to user_path(@user)
  end

  def unfollow
    current_user.followed_users.find_by(followed_id: @user.id).destroy
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :username, :email, :birthday, :status, :first_name, :last_name)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="row">
  <%= form_with model:[:admin, @user],local:true do |f| %>
    <% if @user.errors.present? %>
      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

 <div class="form-group col-md-4 field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, autofocus: true, autocomplete: "birthday", class: "form-control" %>
  </div>

    <div class="form-group col-md-4 field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 file-field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar, autocomplete: "avatar", :id => "image_field", class: "photo_upload form-control" %>
  </div>
  <div>
    <%= image_tag("preview.png", :id => "image_preview", width: 80) %>
  </div>
  <br>
  
    <%= f.submit "Create user", class: "btn btn-outline-primary" %>
    <% end %>
</div>

app/views/admin/users/_search.html.erb
<%= search_form_for @q, url: admin_users_path do |f| %>
    <%= f.search_field :username_or_email_cont %>
    <%= f.label :Permit %>
    <%= f.check_box :status_eq_any, { multiple: true }, 0, '' %>
    <%= f.label :Ban %>
    <%= f.check_box :status_eq_any, { multiple: true }, 1, '' %>
    <%= f.submit "Search", class: "btn btn-outline-info" %>
<% end %>

app/views/admin/users/_table.html.erb
<% @users.each do |user| %>
    <tr>
    <td>
    <% if user.avatar.present? %>
       <%= image_tag(user.avatar, width: 80) %>
     <% end %>
   </td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.birthday %></td>
      <td><%= user.posts.count %></td>
      <td><%= user.groups.count %></td>
      <td><%= user.status %></td>
      <td><%= link_to 'Show', admin_user_path(user) %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", admin_user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>

app/views/admin/users/_tableHeader.html.erb
<tr>
<th>Avatar</th>
<th>Name</th>
<th>Email</th>
<th>Birthday</th>
<th>Total created posts</th>
<th>Total joined groups</th>
<th>Status</th>
<th colspan="3">Actions</th>
</tr>

app/views/admin/users/edit.html.erb
<h1>Update User</h1>
<%= form_with model:[:admin, @user],local:true do |f| %>
  <% if @user.errors.present? %>
      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group col-md-4 field">
    <%= f.label :email %><br />
    <%= f.email_field :email, :readonly => true, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

 <div class="form-group col-md-4 field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, autofocus: true, autocomplete: "birthday", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 field radio-inline">
  <%= f.radio_button :status, :permit, checked: "checked" %>
  <%= f.label :Permit %>
</div>

<div class="form-group col-md-4 field radio-inline">
  <%= f.radio_button :status, :ban %>
  <%= f.label :Ban %>
</div>
<div class="form-group col-md-4 file-field">
<%= f.label :avatar %><br />
<%= f.file_field :avatar, autocomplete: "avatar", :id => "image_field", class: "photo_upload form-control" %>
</div>
<div>
<%= image_tag("preview.png", :id => "image_preview", width: 80) %>
</div>
<br>
  <%= f.submit "Update", class: "btn btn-outline-primary" %>
  <% end %>
  <%= link_to 'Back', admin_posts_path %>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>
<table class="table table-bordered border-primary">
     <thead>
      <%= render 'tableHeader' %>
     </thead>

     <tbody>
      <%= render 'table', user: @user %>
     </tbody>
</table>

   <%= paginate @users %>

   <%= render 'search' %>

<%= link_to 'Create new user', new_admin_user_path %>

<%= link_to "Logout", destroy_user_session_path, "data-turbo-method": :delete %>

app/views/admin/users/new.html.erb
<h1>New User</h1>


<%= render 'form', user: @user %>


<%= link_to 'Back', admin_posts_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @user.family_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Birth date:</strong>
  <%= @user.birthday %>
</p>

<td><%= link_to 'Edit', edit_admin_user_path(@user) %></td>
<%= link_to 'Back', admin_users_path %>