config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    # mount_devise_token_auth_for "User", at: "auth"

    mount_devise_token_auth_for "User", at: "auth", controllers: {
      registrations: "api/users/registrations",
      sessions: "api/users/sessions",
      confirmations: "api/users/confirmations"
    }
    resources :posts, only: [:index]
  end

  devise_for :users
  namespace :admin do
    resources :users
    resources :groups
    resources :posts do
      resources :comments
    end
    # routes for admin
    get 'dashboard/' => 'dashboard#index'
    get 'users/index'
  end
  resources :posts
  resources :groups

  resources :users  do
    member do
      post :follow
      post :unfollow
    end
  end
  
  root 'posts#index'


end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
      <div class="container">
      <!-- Copyright -->
      <div class="text-white text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-white" href="https://www.co-well.jp/">Cowell</a>
      </div>
      <!-- Copyright -->
      </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
	<!-- Collection of nav links, forms, and other content for toggling -->
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
		<div class="navbar-nav">
			<a class="nav-item nav-link"><li><%= link_to "Home", root_path %></li></a>
			<a class="nav-item nav-link"><li><%= link_to "Group", groups_path %></li></a>			
			<a class="nav-item nav-link"><li><%= link_to "Users", users_path %></li></a>
		</div>

		<% if current_page?(root_path) %>
			<%= render 'layouts/search' %>
		<% end %>
		

		<div class="navbar-nav ml-auto action-buttons">
			<a class="nav-item nav-link"><li><%= link_to "Profile", user_path(current_user) %></li></a>
			<% if user_signed_in? %>
				<a class="nav-item nav-link"><li><%= link_to "Logout", destroy_user_session_path, "data-turbo-method": :delete  %></li></a>
			<% else %>
				<a class="nav-item nav-link"><li><%= link_to "Login", new_user_session_path  %></li></a>
			<% end %>
			</div>
        </div>
	</div>
</header>

app/views/layouts/_search.html.erb
<%= search_form_for @q, class: "navbar-form form-inline", url: posts_path do |f| %>
    <div class="input-group search-box">								
      <%= f.search_field :title_cont, id: "search", class: "form-control", placeholder: "Search here..." %>
        <div class="input-group-append">
            <span class="input-group-text">
                <i class="material-icons">&#xE8B6;</i>
            </span>
                <%= f.submit "Search", class: "btn btn-outline-info" %>
                <% end %>
        </div>
    </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>CwBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  <%# this loads Sprockets/Rails asset pipeline %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 
    <%= javascript_importmap_tags %> <%#  this loads JS from importmaps %>
    <!-- CSS only -->
    <!-- JavaScript Bundle with Popper -->
 
  </head>

  <body class="d-flex flex-column h-100">
     <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CwBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  <%# this loads Sprockets/Rails asset pipeline %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    
    <%= javascript_importmap_tags %> <%#  this loads JS from importmaps %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>